#!/bin/bash -x 
echo "***************************************************************************************************************************************************************************************************************************************"

DISPLAY=":0"
HOME=/home/jasalt/
XAUTHORITY=/run/user/1000/gdm/Xauthority

#XAUTHORITY=$HOME/.Xauthority
export DISPLAY XAUTHORITY HOME

# sleep 2
#xset r rate 200 45
# setxkbmap -option ctrl:nocaps

#xmodmap /home/jasalt/dotfiles/linux/Xmodmap
#/bin/sh -c "sleep 5 ; /home/jasalt/dotfiles/linux/bin/thinkstrobo" &

sleep 5

/home/jasalt/dotfiles/linux/input-config.sh
/home/jasalt/dotfiles/linux/bin/thinkstrobo
# sleep 5

# xmodmap /home/jasalt/dotfiles/linux/Xmodmap
# sudo /home/jasalt/dotfiles/linux/input-config.sh

#daskb_id=`xinput -list | grep -i 'daskeyboard' | grep -o id=[0-9]. | grep -o [0-9]. | head -1`
#if [ "${daskb_id}" ]; then
#    setxkbmap -device "${daskb_id}" -option altwin:swap_lalt_lwin
#fi

